# Generated by Django 6.0.3 on 2026-04-25 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('PK_albumID', models.AutoField(db_column='PK_albumID', primary_key=True, serialize=False)),
                ('albumName', models.CharField(db_column='albumName', max_length=100)),
                ('releaseDate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('albumimage', models.ImageField(blank=True, db_column='albumimage', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('PK_artistID', models.AutoField(db_column='PK_artistID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageArtist', models.ImageField(blank=True, db_column='imageArtist', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('PK_bandID', models.AutoField(db_column='PK_bandID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('imageBand', models.ImageField(blank=True, db_column='imageBand', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'band',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('idgeneroMusical', models.AutoField(db_column='idgeneroMusical', primary_key=True, serialize=False)),
                ('nomeGenero', models.CharField(db_column='nomeGenero', max_length=150)),
            ],
            options={
                'db_table': 'generomusical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('PK_playlistID', models.AutoField(db_column='PK_playlistID', primary_key=True, serialize=False)),
                ('plName', models.CharField(blank=True, db_column='plName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('PK_songID', models.AutoField(db_column='PK_songID', primary_key=True, serialize=False)),
                ('songtitle', models.CharField(db_column='songTitle', max_length=150)),
                ('timeMusic', models.TimeField(blank=True, db_column='timeMusic', null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('songpath', models.FileField(blank=True, db_column='songpath', null=True, upload_to='songs/')),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songsplaylist',
            fields=[
                ('PK_songsplaylistID', models.AutoField(db_column='PK_songsplaylistID', primary_key=True, serialize=False)),
                ('ordem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'songsplaylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('PK_userID', models.AutoField(db_column='PK_userID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('senha', models.CharField(max_length=45)),
                ('profilepicture', models.ImageField(blank=True, db_column='profilePicture', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albumartist',
            fields=[
                ('artist_PK_artistID', models.ForeignKey(db_column='artist_PK_artistID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.artist')),
            ],
            options={
                'db_table': 'albumartist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artistsband',
            fields=[
                ('artist_PK_artistID', models.ForeignKey(db_column='artist_PK_artistID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.artist')),
            ],
            options={
                'db_table': 'artistsband',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albumband',
            fields=[
                ('band_PK_bandID', models.ForeignKey(db_column='band_PK_bandID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.band')),
            ],
            options={
                'db_table': 'albumband',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usersplaylists',
            fields=[
                ('users_PK_userID', models.ForeignKey(db_column='users_PK_userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.users')),
            ],
            options={
                'db_table': 'usersplaylists',
                'managed': False,
            },
        ),
    ]
