# Generated by Django 6.0.3 on 2026-04-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('pk_albumid', models.AutoField(db_column='PK_albumID', primary_key=True, serialize=False)),
                ('albumname', models.CharField(db_column='albumName', max_length=100)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
            ],
            options={
                'db_table': 'album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('pk_artistid', models.AutoField(db_column='PK_artistID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageartist', models.CharField(blank=True, db_column='imageArtist', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('pk_bandid', models.AutoField(db_column='PK_bandID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('imageband', models.CharField(blank=True, db_column='imageBand', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'band',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('pk_playlistid', models.AutoField(db_column='PK_playlistID', primary_key=True, serialize=False)),
                ('plname', models.CharField(blank=True, db_column='plName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('pk_songid', models.AutoField(db_column='PK_songID', primary_key=True, serialize=False)),
                ('songtitle', models.CharField(db_column='songTitle', max_length=150)),
                ('timemusic', models.TimeField(blank=True, db_column='timeMusic', null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('generomusical', models.CharField(blank=True, db_column='generoMusical', max_length=45, null=True)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('pk_userid', models.AutoField(db_column='PK_userID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('senha', models.CharField(max_length=45)),
                ('profilepicture', models.CharField(blank=True, db_column='profilePicture', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albummusica',
            fields=[
                ('album', models.ForeignKey(db_column='album_PK_albumID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.album')),
            ],
            options={
                'db_table': 'albummusica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albumartist',
            fields=[
                ('artist', models.ForeignKey(db_column='artist_PK_artistID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.artist')),
            ],
            options={
                'db_table': 'albumartist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artistsband',
            fields=[
                ('artist', models.ForeignKey(db_column='artist_PK_artistID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.artist')),
            ],
            options={
                'db_table': 'artistsband',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albumband',
            fields=[
                ('band', models.ForeignKey(db_column='band_PK_bandID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.band')),
            ],
            options={
                'db_table': 'albumband',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songsplaylist',
            fields=[
                ('playlist', models.ForeignKey(db_column='playlist_PK_playlistID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.playlist')),
            ],
            options={
                'db_table': 'songsplaylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usersplaylists',
            fields=[
                ('users', models.ForeignKey(db_column='users_PK_userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.users')),
            ],
            options={
                'db_table': 'usersplaylists',
                'managed': False,
            },
        ),
    ]
