# Generated by Django 6.0.3 on 2026-04-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('idgeneroMusical', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'generomusical',
            },
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={},
        ),
    ]
